# Generated by Django 4.2.7 on 2024-01-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_organizationtype_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='role',
            field=models.CharField(default='donor', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='role',
            field=models.CharField(default='organization', max_length=50),
        ),
    ]
