# Generated by Django 4.2.7 on 2024-01-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_donor_role_remove_organization_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
